### ISSUE TITLE
Tussenmomentje

### ISSUE THREAD

**Issue by Mennauu** [Mokerstier/browser-technologies-1920#5]
Ik vind het prima dat je in een andere branch werkt. Helemaal niet vervelend. 

_**Ik zit een beetje klem met mijn laatste pagina views/pages/outro.ejs hoe krijg ik die checkboxes nu weer aangevinkt?**_

Bedoel je met je vraag hoe je de checkboxes weer aangevinkt krijgt als je de pagina ververst? Dit kan je doen door op het input element het attribuut `checked` te zetten (op basis van de data uit je JSON, natuurlijk)

Mocht je meer vragen hebben, laat het me weten!

**Comment by Mokerstier** [comment]
Yo het is me al gelukt met die checked btw
ik doe nu heel lelijk dit:
```
 <% if(user.favdoc.includes('BUY')){ %> 
                    <input type="checkbox" name="favdoc" id="Vasilis" value="VaCss" checked>
                    <% } else { %>
                        <input type="checkbox" name="favdoc" id="Vasilis" value="VaCss">
                    <% } %>
```
maar het werkt dus dikke priem

**Comment by Mennauu** [comment]
Ik zou het dan zo schrijven:

```ejs
<input type="checkbox" name="favdoc" id="Vasilis" value="VaCss" <% if(user.favdoc.includes('BUY')){ %> checked <% } %>>
```

**Comment by Mokerstier** [comment]
Aaaah thnx!
deze oplossing zocht ik maar kreeg het niet voor elkaar !
